# Generated by Django 3.2.5 on 2022-08-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('OrbitType', models.CharField(blank=True, max_length=200, null=True)),
                ('OrbitDay', models.FloatField(blank=True, max_length=200, null=True)),
                ('OrbitalPeriod', models.FloatField(blank=True, max_length=200, null=True)),
                ('altitude', models.FloatField(default=0)),
                ('Payload1', models.CharField(blank=True, max_length=200, null=True)),
                ('Payload2', models.CharField(blank=True, max_length=200, null=True)),
                ('Payload3', models.CharField(blank=True, max_length=200, null=True)),
                ('SwathFore', models.FloatField(default=0)),
                ('SwathAft', models.FloatField(default=0)),
                ('IGFOVFore', models.FloatField(default=0)),
                ('IGFOVAft', models.FloatField(default=0)),
                ('TiltFore', models.FloatField(default=0)),
                ('TiltAft', models.FloatField(default=0)),
            ],
        ),
    ]
