# Generated by Django 3.2.15 on 2022-08-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220822_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SatelliteName', models.CharField(blank=True, max_length=200, null=True)),
                ('Application', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='satelliteinfo',
            name='SatelliteId',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='SensorId',
        ),
    ]
