# Generated by Django 3.2.15 on 2022-08-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220824_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Satellite_Application',
        ),
    ]
