# Generated by Django 3.2.15 on 2022-08-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_satellite_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='SwathFore',
            new_name='Swath',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='IGFOVAft',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='IGFOVFore',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='SwathAft',
        ),
        migrations.AddField(
            model_name='sensor',
            name='application',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
