# Generated by Django 3.2.15 on 2022-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220824_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='application',
            new_name='application1',
        ),
        migrations.AddField(
            model_name='sensor',
            name='application2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='application3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
