# Generated by Django 3.2.15 on 2022-08-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220824_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='satelliteinfo',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
